import fs from "node:fs";
import { fileURLToPath } from "node:url";
import type Database from "better-sqlite3";

export const migrationFiles = [
  "0000_init.sql",
  "0001_phase1.sql",
  "0002_phase2.sql",
  "0003_phase3.sql",
  "0004_comments_fks.sql",
  "0005_password_resets.sql",
  "0006_transcode_notify.sql",
  "0007_project_cover.sql",
  "0008_project_cover_blob.sql",
  "0009_share_folders.sql",
  "0010_project_cover_uploads.sql",
  "0011_user_avatars.sql",
  "0012_caption_tracks.sql",
  "0013_user_totp.sql",
  "0014_app_settings.sql",
  "0015_guest_accounts.sql",
  "0016_transfers.sql",
  "0017_public_ids.sql",
  "0018_share_approvals.sql",
  "0019_asset_thumbnails.sql",
  "0020_audio_renditions.sql",
  "0021_transfer_access.sql",
  "0022_shares_project_index.sql",
];

const migrationPath = (file: string): string =>
  fileURLToPath(new URL(`../migrations/${file}`, import.meta.url));

export const readMigrationFile = (file: string): string =>
  fs.readFileSync(migrationPath(file), "utf8");

const BREAKPOINT = "--> statement-breakpoint";

/**
 * Split a migration file into individual statements. Files generated by
 * drizzle-kit are split on their explicit statement-breakpoint markers.
 * Hand-written files fall back to a scanner that only treats ";" as a
 * terminator outside string literals, quoted identifiers, and comments.
 */
export const splitSqlStatements = (sqlText: string): string[] => {
  const rawStatements = sqlText.includes(BREAKPOINT)
    ? sqlText.split(BREAKPOINT)
    : scanStatements(sqlText);
  return rawStatements
    .map((statement) => statement.replace(/;\s*$/, "").trim())
    .filter((statement) => normalizeSqlStatement(statement).length > 0);
};

const scanStatements = (sqlText: string): string[] => {
  const statements: string[] = [];
  let start = 0;
  let index = 0;
  const length = sqlText.length;
  while (index < length) {
    const char = sqlText[index];
    if (char === "'" || char === '"' || char === "`") {
      // String literal or quoted identifier: doubled quotes escape the quote.
      index += 1;
      while (index < length) {
        if (sqlText[index] === char) {
          if (sqlText[index + 1] === char) {
            index += 2;
            continue;
          }
          break;
        }
        index += 1;
      }
      index += 1;
      continue;
    }
    if (char === "-" && sqlText[index + 1] === "-") {
      const newline = sqlText.indexOf("\n", index);
      index = newline === -1 ? length : newline + 1;
      continue;
    }
    if (char === "/" && sqlText[index + 1] === "*") {
      const close = sqlText.indexOf("*/", index + 2);
      index = close === -1 ? length : close + 2;
      continue;
    }
    if (char === ";") {
      statements.push(sqlText.slice(start, index));
      index += 1;
      start = index;
      continue;
    }
    index += 1;
  }
  statements.push(sqlText.slice(start));
  return statements;
};

/**
 * Normalization used to compare statements across representations: strips
 * comments and breakpoint markers, collapses whitespace, and drops the
 * trailing semicolon.
 */
export const normalizeSqlStatement = (statement: string): string =>
  statement
    .replace(/--[^\n]*/g, " ")
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/\s+/g, " ")
    .replace(/;\s*$/, "")
    .trim();

/* The migration files not yet recorded in __onelight_migrations. Read before
   applyNodeMigrations so a caller can snapshot the DB when a deploy is about to
   change the schema -- the rollback path for irreversible table rebuilds is to
   restore that snapshot, not a down-migration that cannot exist. Returns [] on
   a fresh DB with no tracking table (nothing to roll back to). */
export const pendingMigrations = (sqlite: Database.Database): string[] => {
  const hasTracking = sqlite
    .prepare(
      "SELECT 1 FROM sqlite_master WHERE type='table' AND name='__onelight_migrations'",
    )
    .get();
  if (!hasTracking) return migrationFiles.slice();
  const isApplied = sqlite.prepare(
    "SELECT 1 FROM __onelight_migrations WHERE id = ?",
  );
  return migrationFiles.filter((file) => !isApplied.get(file));
};

export const applyNodeMigrations = (sqlite: Database.Database): void => {
  sqlite.exec(
    "CREATE TABLE IF NOT EXISTS __onelight_migrations (id TEXT PRIMARY KEY)",
  );
  const oldSchema = sqlite
    .prepare(
      "SELECT 1 FROM sqlite_master WHERE type='table' AND name='workspaces'",
    )
    .get();
  if (
    oldSchema &&
    !sqlite
      .prepare("SELECT 1 FROM __onelight_migrations WHERE id = '0000_init.sql'")
      .get()
  )
    sqlite
      .prepare(
        "INSERT INTO __onelight_migrations (id) VALUES ('0000_init.sql')",
      )
      .run();
  const isApplied = sqlite.prepare(
    "SELECT 1 FROM __onelight_migrations WHERE id = ?",
  );
  const trackApplied = sqlite.prepare(
    "INSERT INTO __onelight_migrations (id) VALUES (?)",
  );
  for (const file of migrationFiles) {
    if (isApplied.get(file)) continue;
    const statements = splitSqlStatements(readMigrationFile(file));
    // Each migration file runs inside one transaction so a mid-file failure
    // rolls back cleanly instead of leaving an untracked half-applied schema.
    const applyFile = sqlite.transaction(() => {
      for (const statement of statements) sqlite.exec(statement);
      trackApplied.run(file);
    });
    applyFile();
  }
};
