/* Integration tests that actually run ffmpeg/ffprobe, as opposed to media.test.ts
   which only checks the argument builders. These exercise the runtime paths --
   spawning, output capture, the temp-and-rename contract, and the inactivity
   watchdog -- against a real one-second clip generated by ffmpeg's lavfi source.
   Skipped where no ffmpeg is on PATH so a bare dev box does not fail the run;
   they do run in the worker image, which is where the suite executes on nyx. */
import { spawnSync } from "node:child_process";
import { mkdtemp, rm, stat } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { extractStill, probeFile, runProcess } from "./media.js";

const ffmpeg = process.env.FFMPEG_PATH ?? "ffmpeg";
const ffprobe = process.env.FFPROBE_PATH ?? "ffprobe";
const hasFfmpeg =
  spawnSync(ffmpeg, ["-version"]).status === 0 &&
  spawnSync(ffprobe, ["-version"]).status === 0;

/* A 1s 320x240 24fps test clip written to `dir/source.mp4`. */
const makeClip = async (dir: string): Promise<string> => {
  const source = path.join(dir, "source.mp4");
  await runProcess(ffmpeg, [
    "-f",
    "lavfi",
    "-i",
    "testsrc=duration=1:size=320x240:rate=24",
    "-pix_fmt",
    "yuv420p",
    "-y",
    source,
  ]);
  return source;
};

describe.skipIf(!hasFfmpeg)("media integration (real ffmpeg)", () => {
  it("probes a real clip's stream geometry and duration", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const info = await probeFile(source);
      const video = info.streams.find(
        (stream) => stream.codec_type === "video",
      );
      expect(video?.width).toBe(320);
      expect(video?.height).toBe(240);
      // ~1s; ffmpeg may land a frame either side, so allow a small window.
      expect(Number(info.format.duration)).toBeGreaterThan(0.8);
      expect(Number(info.format.duration)).toBeLessThan(1.3);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("extracts a non-empty still and lands it at the final path", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const poster = path.join(dir, "poster.png");
      await extractStill(source, poster, 5, { num: 24, den: 1 });
      const info = await stat(poster);
      expect(info.size).toBeGreaterThan(0);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("kills and fails a process that goes silent past the idle timeout", async () => {
    // `sleep` produces no output, so the inactivity watchdog is what ends it:
    // a 5s sleep is SIGKILLed after 200ms and the promise rejects, rather than
    // the test waiting the full five seconds.
    const started = Date.now();
    await expect(
      runProcess("sleep", ["5"], undefined, 200),
    ).rejects.toThrow(/hung/);
    expect(Date.now() - started).toBeLessThan(2000);
  });

  it("does not trip the watchdog on a working encode", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      // A real encode emits progress on stderr, which keeps resetting the idle
      // timer, so even a tight timeout does not fire on genuine work.
      await expect(makeClip(dir)).resolves.toBeDefined();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
