/* Integration tests that actually run ffmpeg/ffprobe, as opposed to media.test.ts
   which only checks the argument builders. These exercise the runtime paths --
   spawning, output capture, the temp-and-rename contract, and the inactivity
   watchdog -- against a real one-second clip generated by ffmpeg's lavfi source.
   Skipped where no ffmpeg is on PATH so a bare dev box does not fail the run;
   they do run in the worker image, which is where the suite executes on nyx. */
import { spawnSync } from "node:child_process";
import { mkdtemp, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  exactWebCodecString,
  extractStill,
  planRenditions,
  probeFile,
  runProcess,
  runTranscode,
} from "./media.js";
import { CLIP_HASH_POSITIONS } from "./fingerprint-media.js";
import {
  AUDIO_MATCH_MAX_DISTANCE,
  contentDistance,
  hashDistance,
} from "@onelight/core";

const ffmpeg = process.env.FFMPEG_PATH ?? "ffmpeg";
const ffprobe = process.env.FFPROBE_PATH ?? "ffprobe";
const hasFfmpeg =
  spawnSync(ffmpeg, ["-version"]).status === 0 &&
  spawnSync(ffprobe, ["-version"]).status === 0;

/* A 1s 320x240 24fps test clip written to `dir/source.mp4`. */
const makeClip = async (dir: string): Promise<string> => {
  const source = path.join(dir, "source.mp4");
  await runProcess(ffmpeg, [
    "-f",
    "lavfi",
    "-i",
    "testsrc=duration=1:size=320x240:rate=24",
    "-pix_fmt",
    "yuv420p",
    "-y",
    source,
  ]);
  return source;
};

describe.skipIf(!hasFfmpeg)("media integration (real ffmpeg)", () => {
  it("probes a real clip's stream geometry and duration", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const info = await probeFile(source);
      const video = info.streams.find(
        (stream) => stream.codec_type === "video",
      );
      expect(video?.width).toBe(320);
      expect(video?.height).toBe(240);
      // ~1s; ffmpeg may land a frame either side, so allow a small window.
      expect(Number(info.format.duration)).toBeGreaterThan(0.8);
      expect(Number(info.format.duration)).toBeLessThan(1.3);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("reads the exact WebCodecs string from the encoded container", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      await expect(exactWebCodecString(source)).resolves.toMatch(
        /^avc1\.[0-9a-f]{6}$/i,
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("extracts a non-empty still and lands it at the final path", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const poster = path.join(dir, "poster.png");
      await extractStill(source, poster, 5, { num: 24, den: 1 });
      const info = await stat(poster);
      expect(info.size).toBeGreaterThan(0);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("kills and fails a process that goes silent past the idle timeout", async () => {
    // `sleep` produces no output, so the inactivity watchdog is what ends it:
    // a 5s sleep is SIGKILLed after 200ms and the promise rejects, rather than
    // the test waiting the full five seconds.
    const started = Date.now();
    await expect(runProcess("sleep", ["5"], undefined, 200)).rejects.toThrow(
      /hung/,
    );
    expect(Date.now() - started).toBeLessThan(2000);
  });

  it("does not trip the watchdog on a working encode", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      // A real encode emits progress on stderr, which keeps resetting the idle
      // timer, so even a tight timeout does not fire on genuine work.
      await expect(makeClip(dir)).resolves.toBeDefined();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  /* The stills ladder through the same entry point the pump calls, on the two
     source families that reach it by different routes: a JPEG that sharp opens
     directly, and a PSD that only ffmpeg can decode. Before this, a JPEG's
     poster was silently never written at all. */
  const stillRoundTrip = async (
    name: string,
    make: (file: string) => Promise<void>,
  ): Promise<void> => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-still-"));
    try {
      const source = path.join(dir, name);
      await make(source);
      const info = await probeFile(source);
      const planned = planRenditions("image", info);
      expect(planned.map((entry) => entry.kind)).toEqual([
        "poster",
        "still_review",
      ]);
      const outputs = planned.map((entry) => ({
        kind: entry.kind,
        path: path.join(dir, "renditions", entry.filename),
      }));
      const result = await runTranscode(
        {
          id: "job",
          sourceKey: source,
          outputs: outputs.map((output) => ({
            kind: output.kind,
            key: output.path,
          })),
          mediaInfo: info,
        },
        outputs,
      );
      expect(result.failures).toEqual([]);
      expect(
        result.renditions.map((rendition) => rendition.kind).sort(),
      ).toEqual(["poster", "still_review"]);
      /* The identity comes back beside the renditions, for every format the
         ladder can render. Taking it with sharp alone left PSD, RAW and HEIC
         with no identity at all, which are the formats most likely to arrive
         as a renamed second pass. */
      expect(result.fingerprint?.content_hash).toMatch(/^[0-9a-f]{16}$/);
      for (const output of outputs)
        expect((await stat(output.path)).size).toBeGreaterThan(0);
      /* The intermediate ffmpeg decode a PSD needs must not be left in the
         rendition directory: nothing references it and the GC would keep it
         forever. */
      const stray = await readdir(path.join(dir, "renditions"));
      expect(stray.filter((entry) => entry.startsWith("."))).toEqual([]);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  };

  it("renders the ladder for a JPEG source", async () => {
    await stillRoundTrip("frame.jpg", async (file) => {
      await runProcess(ffmpeg, [
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=1600x1000:d=1",
        "-frames:v",
        "1",
        "-y",
        file,
      ]);
    });
  });

  it("renders the ladder for a PSD source", async () => {
    await stillRoundTrip("layered.psd", async (file) => {
      const width = 320;
      const height = 200;
      const header = Buffer.concat([
        Buffer.from("8BPS", "ascii"),
        Buffer.from([0, 1]),
        Buffer.alloc(6),
        Buffer.from([0, 3]),
        (() => {
          const value = Buffer.alloc(4);
          value.writeUInt32BE(height);
          return value;
        })(),
        (() => {
          const value = Buffer.alloc(4);
          value.writeUInt32BE(width);
          return value;
        })(),
        Buffer.from([0, 8]),
        Buffer.from([0, 3]),
        Buffer.alloc(12),
        Buffer.from([0, 0]),
      ]);
      const plane = Buffer.alloc(width * height, 180);
      await writeFile(file, Buffer.concat([header, plane, plane, plane]));
    });
  });

  it("returns a clip's identity beside its renditions", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = path.join(dir, "clip.mp4");
      await runProcess(ffmpeg, [
        "-f",
        "lavfi",
        "-i",
        "testsrc2=duration=6:size=320x240:rate=12",
        "-pix_fmt",
        "yuv420p",
        "-metadata",
        "creation_time=2026-07-29T14:03:11.470000Z",
        "-y",
        source,
      ]);
      const info = await probeFile(source);
      const outputs = [
        {
          kind: "proxy_540",
          path: path.join(dir, "proxy_540.mp4"),
          height: 540,
        },
      ];
      const result = await runTranscode(
        {
          id: "clip-job",
          sourceKey: source,
          outputs: outputs.map((output) => ({
            kind: output.kind,
            key: output.path,
          })),
          mediaInfo: info,
        },
        outputs,
      );
      /* One hash per sampling point along the clip: a shot list, not a
         signature. */
      expect(result.fingerprint?.content_hash?.split(":")).toHaveLength(
        CLIP_HASH_POSITIONS.length,
      );
      expect(result.fingerprint?.content_hash).toMatch(
        /^[0-9a-f]{16}(:[0-9a-f]{16})+$/,
      );
      /* Nothing named a camera, so the creation time is a render's and buys
         no identity. This is the four-spots case: every export this
         afternoon carries this afternoon. */
      expect(result.fingerprint?.capture_key ?? null).toBeNull();
      /* Silent, so no audio hash: a slate must not match every other slate. */
      expect(result.fingerprint?.audio_hash ?? null).toBeNull();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("identifies a camera original by its tags and a graded copy by its sound", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-audio-"));
    try {
      /* mp4 and mov drop tags they do not know unless asked to keep them,
         which is why this writes .mov with use_metadata_tags: a real camera
         file carries make and model in udta. */
      const make = (name: string, extra: string[]): string => {
        const file = path.join(dir, name);
        spawnSync("ffmpeg", [
          "-hide_banner",
          "-loglevel",
          "error",
          "-f",
          "lavfi",
          "-i",
          "testsrc2=duration=6:size=320x240:rate=12",
          "-f",
          "lavfi",
          "-i",
          "sine=frequency=320:duration=6,tremolo=f=1.7:d=0.9",
          "-pix_fmt",
          "yuv420p",
          "-shortest",
          "-movflags",
          "use_metadata_tags",
          "-metadata",
          "creation_time=2026-07-29T14:03:11.470000Z",
          ...extra,
          "-y",
          file,
        ]);
        return file;
      };
      /* The camera original: something named the body, so its time counts. */
      const original = make("A001C001.mov", [
        "-metadata",
        "make=Blackmagic Design",
        "-metadata",
        "model=URSA Mini Pro",
      ]);
      /* The grade that comes back: no camera tags any more, a different
         picture, the same audio. */
      const graded = make("HERO_CC_v2.mov", [
        "-vf",
        "eq=brightness=0.12:saturation=1.4",
      ]);
      const sign = async (file: string) => {
        const info = await probeFile(file);
        const outputs = [
          {
            kind: "proxy_540",
            path: path.join(dir, `${path.basename(file)}-proxy.mp4`),
            height: 540,
          },
        ];
        return runTranscode(
          {
            id: `job-${path.basename(file)}`,
            sourceKey: file,
            outputs: outputs.map((output) => ({
              kind: output.kind,
              key: output.path,
            })),
            mediaInfo: info,
          },
          outputs,
        );
      };
      const first = await sign(original);
      const second = await sign(graded);
      /* A camera vouched for the time, so there is an identity. */
      expect(first.fingerprint?.capture_key).toContain("2026-07-29t14:03:11");
      expect(first.fingerprint?.capture_key).toContain("blackmagic");
      expect(second.fingerprint?.capture_key ?? null).toBeNull();
      /* The grade moved the picture and left the sound alone, which is the
         whole reason sound sits above picture for a colour pass. */
      expect(
        hashDistance(
          first.fingerprint?.audio_hash as string,
          second.fingerprint?.audio_hash as string,
        ),
      ).toBeLessThanOrEqual(AUDIO_MATCH_MAX_DISTANCE);
      expect(
        contentDistance(
          first.fingerprint?.content_hash as string,
          second.fingerprint?.content_hash as string,
        ),
      ).toBeGreaterThan(0);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }, 120_000);
});
