/* Integration tests that actually run ffmpeg/ffprobe, as opposed to media.test.ts
   which only checks the argument builders. These exercise the runtime paths --
   spawning, output capture, the temp-and-rename contract, and the inactivity
   watchdog -- against a real one-second clip generated by ffmpeg's lavfi source.
   Skipped where no ffmpeg is on PATH so a bare dev box does not fail the run;
   they do run in the worker image, which is where the suite executes on nyx. */
import { spawnSync } from "node:child_process";
import { mkdtemp, readdir, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  exactWebCodecString,
  extractStill,
  planRenditions,
  probeFile,
  runProcess,
  runTranscode,
} from "./media.js";

const ffmpeg = process.env.FFMPEG_PATH ?? "ffmpeg";
const ffprobe = process.env.FFPROBE_PATH ?? "ffprobe";
const hasFfmpeg =
  spawnSync(ffmpeg, ["-version"]).status === 0 &&
  spawnSync(ffprobe, ["-version"]).status === 0;

/* A 1s 320x240 24fps test clip written to `dir/source.mp4`. */
const makeClip = async (dir: string): Promise<string> => {
  const source = path.join(dir, "source.mp4");
  await runProcess(ffmpeg, [
    "-f",
    "lavfi",
    "-i",
    "testsrc=duration=1:size=320x240:rate=24",
    "-pix_fmt",
    "yuv420p",
    "-y",
    source,
  ]);
  return source;
};

describe.skipIf(!hasFfmpeg)("media integration (real ffmpeg)", () => {
  it("probes a real clip's stream geometry and duration", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const info = await probeFile(source);
      const video = info.streams.find(
        (stream) => stream.codec_type === "video",
      );
      expect(video?.width).toBe(320);
      expect(video?.height).toBe(240);
      // ~1s; ffmpeg may land a frame either side, so allow a small window.
      expect(Number(info.format.duration)).toBeGreaterThan(0.8);
      expect(Number(info.format.duration)).toBeLessThan(1.3);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("reads the exact WebCodecs string from the encoded container", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      await expect(exactWebCodecString(source)).resolves.toMatch(
        /^avc1\.[0-9a-f]{6}$/i,
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("extracts a non-empty still and lands it at the final path", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = await makeClip(dir);
      const poster = path.join(dir, "poster.png");
      await extractStill(source, poster, 5, { num: 24, den: 1 });
      const info = await stat(poster);
      expect(info.size).toBeGreaterThan(0);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("kills and fails a process that goes silent past the idle timeout", async () => {
    // `sleep` produces no output, so the inactivity watchdog is what ends it:
    // a 5s sleep is SIGKILLed after 200ms and the promise rejects, rather than
    // the test waiting the full five seconds.
    const started = Date.now();
    await expect(runProcess("sleep", ["5"], undefined, 200)).rejects.toThrow(
      /hung/,
    );
    expect(Date.now() - started).toBeLessThan(2000);
  });

  it("does not trip the watchdog on a working encode", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      // A real encode emits progress on stderr, which keeps resetting the idle
      // timer, so even a tight timeout does not fire on genuine work.
      await expect(makeClip(dir)).resolves.toBeDefined();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  /* The stills ladder through the same entry point the pump calls, on the two
     source families that reach it by different routes: a JPEG that sharp opens
     directly, and a PSD that only ffmpeg can decode. Before this, a JPEG's
     poster was silently never written at all. */
  const stillRoundTrip = async (
    name: string,
    make: (file: string) => Promise<void>,
  ): Promise<void> => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-still-"));
    try {
      const source = path.join(dir, name);
      await make(source);
      const info = await probeFile(source);
      const planned = planRenditions("image", info);
      expect(planned.map((entry) => entry.kind)).toEqual([
        "poster",
        "still_review",
      ]);
      const outputs = planned.map((entry) => ({
        kind: entry.kind,
        path: path.join(dir, "renditions", entry.filename),
      }));
      const result = await runTranscode(
        {
          id: "job",
          sourceKey: source,
          outputs: outputs.map((output) => ({
            kind: output.kind,
            key: output.path,
          })),
          mediaInfo: info,
        },
        outputs,
      );
      expect(result.failures).toEqual([]);
      expect(
        result.renditions.map((rendition) => rendition.kind).sort(),
      ).toEqual(["poster", "still_review"]);
      /* The identity comes back beside the renditions, for every format the
         ladder can render. Taking it with sharp alone left PSD, RAW and HEIC
         with no identity at all, which are the formats most likely to arrive
         as a renamed second pass. */
      expect(result.fingerprint?.content_hash).toMatch(/^[0-9a-f]{16}$/);
      for (const output of outputs)
        expect((await stat(output.path)).size).toBeGreaterThan(0);
      /* The intermediate ffmpeg decode a PSD needs must not be left in the
         rendition directory: nothing references it and the GC would keep it
         forever. */
      const stray = await readdir(path.join(dir, "renditions"));
      expect(stray.filter((entry) => entry.startsWith("."))).toEqual([]);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  };

  it("renders the ladder for a JPEG source", async () => {
    await stillRoundTrip("frame.jpg", async (file) => {
      await runProcess(ffmpeg, [
        "-f",
        "lavfi",
        "-i",
        "testsrc2=size=1600x1000:d=1",
        "-frames:v",
        "1",
        "-y",
        file,
      ]);
    });
  });

  it("renders the ladder for a PSD source", async () => {
    await stillRoundTrip("layered.psd", async (file) => {
      const width = 320;
      const height = 200;
      const header = Buffer.concat([
        Buffer.from("8BPS", "ascii"),
        Buffer.from([0, 1]),
        Buffer.alloc(6),
        Buffer.from([0, 3]),
        (() => {
          const value = Buffer.alloc(4);
          value.writeUInt32BE(height);
          return value;
        })(),
        (() => {
          const value = Buffer.alloc(4);
          value.writeUInt32BE(width);
          return value;
        })(),
        Buffer.from([0, 8]),
        Buffer.from([0, 3]),
        Buffer.alloc(12),
        Buffer.from([0, 0]),
      ]);
      const plane = Buffer.alloc(width * height, 180);
      await writeFile(file, Buffer.concat([header, plane, plane, plane]));
    });
  });

  it("returns a clip's identity beside its renditions", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "onelight-mi-"));
    try {
      const source = path.join(dir, "clip.mp4");
      await runProcess(ffmpeg, [
        "-f",
        "lavfi",
        "-i",
        "testsrc2=duration=6:size=320x240:rate=12",
        "-pix_fmt",
        "yuv420p",
        "-metadata",
        "creation_time=2026-07-29T14:03:11.470000Z",
        "-y",
        source,
      ]);
      const info = await probeFile(source);
      const outputs = [
        {
          kind: "proxy_540",
          path: path.join(dir, "proxy_540.mp4"),
          height: 540,
        },
      ];
      const result = await runTranscode(
        {
          id: "clip-job",
          sourceKey: source,
          outputs: outputs.map((output) => ({
            kind: output.kind,
            key: output.path,
          })),
          mediaInfo: info,
        },
        outputs,
      );
      /* Four hashes, one per sampling point along the clip. */
      expect(result.fingerprint?.content_hash).toMatch(
        /^[0-9a-f]{16}(:[0-9a-f]{16}){3}$/,
      );
      /* And the creation time the file carries, which a re-export keeps. */
      expect(result.fingerprint?.capture_key).toContain("2026-07-29t14:03:11");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
