/*
 * OpenAPI codegen. Boots the app in-process on an in-memory database,
 * captures /api/v1/openapi.json, writes packages/api/openapi.json, and runs
 * openapi-typescript into packages/web/src/lib/api-types.gen.ts. Both files
 * are committed; CI runs the check mode so they cannot go stale.
 *
 * Usage (repo root):
 *   pnpm openapi:gen     regenerate both committed artifacts
 *   pnpm openapi:check   regenerate in memory and diff (nonzero exit on drift)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import {
  Pbkdf2PasswordHasher,
  UlidGenerator,
  loadConfig,
  systemClock,
} from "@onelight/core";
import { applyNodeMigrations, createNodeDb } from "@onelight/db";
import { createApp } from "./app.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..", "..");
const openapiPath = path.join(repoRoot, "packages", "api", "openapi.json");
const typesPath = path.join(
  repoRoot,
  "packages",
  "web",
  "src",
  "lib",
  "api-types.gen.ts",
);

const buildDocument = async (): Promise<string> => {
  const { db, sqlite } = createNodeDb(":memory:");
  applyNodeMigrations(sqlite);
  const app = createApp({
    db,
    hasher: new Pbkdf2PasswordHasher(),
    clock: systemClock,
    ids: new UlidGenerator(),
    config: loadConfig({
      PUBLIC_URL: "http://onelight.local",
      SECRET_KEY: "openapi-codegen-secret-key-with-32-plus-chars",
    }),
    // Fixed so the committed document does not churn with app versions.
    version: "0.1.0",
  });
  const response = await app.request("/api/v1/openapi.json");
  if (response.status !== 200)
    throw new Error(`openapi.json request failed: ${response.status}`);
  const document = (await response.json()) as Record<string, unknown>;
  sqlite.close();
  return JSON.stringify(document, null, 2) + "\n";
};

const buildTypes = async (documentJson: string): Promise<string> => {
  const ast = await openapiTS(JSON.parse(documentJson));
  const banner =
    "/* Generated by `pnpm openapi:gen` from packages/api/openapi.json. Do not edit. */\n\n";
  return banner + astToString(ast);
};

const readOrEmpty = (file: string): string => {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
};

const main = async (): Promise<void> => {
  const check = process.argv.includes("--check");
  const documentJson = await buildDocument();
  const types = await buildTypes(documentJson);
  if (check) {
    const stale: string[] = [];
    if (readOrEmpty(openapiPath) !== documentJson) stale.push(openapiPath);
    if (readOrEmpty(typesPath) !== types) stale.push(typesPath);
    if (stale.length) {
      console.error(
        "OpenAPI artifacts are stale. Run `pnpm openapi:gen` and commit:",
      );
      for (const file of stale) console.error(`  ${file}`);
      process.exit(1);
    }
    console.log("openapi:check ok");
    return;
  }
  writeFileSync(openapiPath, documentJson);
  writeFileSync(typesPath, types);
  console.log(`wrote ${openapiPath}`);
  console.log(`wrote ${typesPath}`);
};

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
